
# Challenge #6: Spatial Route

>We hope you enjoyed last week's challenge.   For the sixth challenge lets look at some of the geospatial capabilities in Alteryx.

>The challenge for week 6 will focus on analyzing distance traveled by sales reps.

>Sales reps are travelling all over the US. The data contained in the workflow details the travel paths for 7 Reps to 7 different cities. The travel route is detailed as well. The objective of this challenge is to **determine which Rep has logged the most miles. Please include the route traveled as a spatial object in the output.**

>We have listed this as an intermediate challenge since not everyone is familiar with the Spatial tools.  As always, we love to hear your comments. We hope you are having fun with the challenges!

In [1]:
import pandas as pd

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

     REP     LengthMi
0  Diana  9077.844095
1  Cathy  6777.003786
2    Dan  6220.995173
3  James  6157.018626
4  Steve  4250.389398
5  Scott  4178.885363
6   Mark  3210.917267

In [2]:
# import and preview input

input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df.head(25)

                                         Airport City    REP  TripOrder
0      Hartford-West Hartford-East Hartford, CT Metro  Cathy          1
1              Indianapolis-Carmel-Anderson, IN Metro  Cathy          2
2                               Springfield, MA Metro  Cathy          3
3                                      Reno, NV Metro  Cathy          4
4                          Cleveland-Elyria, OH Metro  Cathy          5
5                                 Knoxville, TN Metro  Cathy          6
6                                   Madison, WI Metro  Cathy          7
7                   Phoenix-Mesa-Scottsdale, AZ Metro    Dan          1
8     Miami-Fort Lauderdale-West Palm Beach, FL Metro    Dan          2
9                         Lexington-Fayette, KY Metro    Dan          3
10                                  Jackson, MS Metro    Dan          4
11                              Albuquerque, NM Metro    Dan          5
12                               Pittsburgh, PA Metro    Dan          6
13              Burlington-South Burlington, VT Metro    Dan          7
14           Los Angeles-Long Beach-Anaheim, CA Metro  Diana          1
15                               Boise City, ID Metro  Diana          2
16                                   Bangor, ME Metro  Diana          3
17                                 Billings, MT Metro  Diana          4
18                       Durham-Chapel Hill, NC Metro  Diana          5
19  Myrtle Beach-Conway-North Myrtle Beach, SC-NC ...  Diana          6
20                  Seattle-Tacoma-Bellevue, WA Metro  Diana          7
21                               Tuscaloosa, AL Metro  James          1
22  Washington-Arlington-Alexandria, DC-VA-MD-WV M...  James          2
23                                   Topeka, KS Metro  James          3
24      Minneapolis-St. Paul-Bloomington, MN-WI Metro  James          4