
# Challenge #8: Aggregate Consumer Purchases

### Aggregate Consumer Purchases:

>For this week’s exercise we will look at customer purchase behavior to decide if we should offer a “Meal Deal” that would add a side and drink to a purchase of pizza or a burger. The incoming data is larger than usual for these exercises so I have packaged the workflow as an Alteryx Package.

### This week’s Objective:

>In order to decide if we should start including a new "Meal Deal" on our menu we want to study the potential impact on recent transactions. **Please identify the number and percentage of orders since July 1, 2013 which include the following categories of food: Pizza OR Burger along with a Side and Drink.**

### Summary of Data:

>Point of Sale data includes the ticket level information, and the lookup table categorizes items into higher level food categories.

#### Hint:

>Don't forget to join to the lookup table and filter by date. As always we look forward to your feedback and suggestions!

In [1]:
import pandas as pd

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

   Potential Meal Deal  Total          %
0                10964  15497  70.749177

In [3]:
# import and preview input

input = pd.read_csv('input1.csv', index_col = False)
df = pd.DataFrame(input)
df.head(10)

   TicketID        Date  MemberID                       Desc  Price
0    100004  2013-01-07       NaN          Mozzarella Sticks    7.0
1    100004  2013-01-07       NaN           Jalapeno Poppers    7.0
2    100004  2013-01-07       NaN                Onion Rings    7.0
3    100004  2013-01-07       NaN                Onion Rings    7.0
4    100004  2013-01-07       NaN            Supreme - Small    9.0
5    100004  2013-01-07       NaN            Supreme - Large   16.0
6    100004  2013-01-07       NaN      Mt. Hawaiian - Medium   14.0
7    100004  2013-01-07       NaN  Barbecue Chicken - Medium   14.0
8    100004  2013-01-07       NaN  Barbecue Chicken - Medium   14.0
9    100004  2013-01-07       NaN  Barbecue Chicken - Medium   14.0

In [4]:
# import and preview input

input2 = pd.read_csv('input2.csv', index_col = False)
df2 = pd.DataFrame(input2)
df2.head(10)

                        Desc    Type
0               Bacon Burger  Burger
1   Barbecue Chicken - Large   Pizza
2  Barbecue Chicken - Medium   Pizza
3   Barbecue Chicken - Small   Pizza
4    Buffalo Chicken - Large   Pizza
5   Buffalo Chicken - Medium   Pizza
6    Buffalo Chicken - Small   Pizza
7              Caprese Salad   Salad
8               Cheese Bread    Side
9              Cheese Burger  Burger

In [ ]:
# join data together
# group by order, aggregate item types
# filter to records with [[Pizza | Burger] & Side & Drink]
# count, get percent of total