# Challenge #5: HR Position Finder Application

>We hope you enjoyed last week's challenge. For the fifth challenge let’s look at building an analytic application.

>An HR department has a defined hierarchy for job identification across the organization. Depending on the job, the position within the hierarchy can change.

>The goal is to **create an analytical application that allows a HR rep to enter a position # (in this example, 33333) and return all records where the position is found within the hierarchy system.**

>We have listed this as an intermediate challenge since parameterizing a workflow and converting it to an application is slightly more advanced however the workflow to answer the question should be beginner level. As always, we love to hear your comments. We hope you are having fun with the challenges!

In [3]:
import pandas as pd

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

   Position Number  Level0  Level1  Level2  Level3
0            33333  123456  111111   22222   33333
1            33333  123456   12222   33333   36677
2            33333  123456   33333  235555  388888

In [4]:
# import and preview input

input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df.head(25)

    Level0    Level1    Level2     Level3
0   123456       NaN       NaN        NaN
1   123456  111111.0       NaN        NaN
2   123456  111111.0   22222.0        NaN
3   123456  111111.0   22222.0    33333.0
4   123456  111111.0   23333.0        NaN
5   123456  111111.0   23333.0    34444.0
6   123456  111111.0   23333.0    35555.0
7   123456   12222.0       NaN        NaN
8   123456   12222.0  234444.0        NaN
9   123456   12222.0  234444.0   366666.0
10  123456   12222.0   33333.0    36677.0
11  123456   12222.0  234444.0    37777.0
12  123456   12222.0       NaN        NaN
13  123456   12222.0  235555.0        NaN
14  123456   12222.0  235555.0   388888.0
15  123456   12222.0  235555.0   399999.0
16  123456   12222.0  235555.0   399888.0
17  123456   12222.0  235555.0  3998877.0
18  123456   33333.0  235555.0   388888.0

In [ ]:
# return row where includes ######